# Generated by Django 4.0.4 on 2022-06-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_feedback_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Введите имю')),
                ('callback', models.CharField(max_length=200, verbose_name='Контакт для обратной связи')),
                ('client_message', models.TextField(max_length=1000, verbose_name='Сообщение')),
            ],
        ),
    ]
